### PR TITLE
Fix setup

### PR DESCRIPTION
**Pull request by sanzoghenzo**
This will hopefully fix the installation issue reported in #125.

The remote debugger was enabled, I added an environment variable to avoid rogue commits (and updated the readme accordingly).

I also took the liberty to make things more pythonic (mostly PEP8 naming style) and make the setup code DRY.

### CODE REVIEW

**Comment by KatKatKateryna** [comment]
Hi @sanzoghenzo ! Glad it worked in the end. 
Thanks for the contribution! There are some changes already piled up, I will take a look at PR right after they are merged, this or next week. Would you mind sharing which documentation you followed to make the accounts work on linux?

**Comment by sanzoghenzo** [comment]
Sorry, I thought I posted it already, it may be lost in my many edits :sweat_smile: 

[Here it is](https://speckle.guide/user/manager.html#adding-accounts-manually)

**Comment by sanzoghenzo** [comment]
Hi, I hope it's OK that I just force-pushed the branch of this PR with what you asked.

I'm looking forward to see the new changes you have in store!

If I may ask, what's the

**Comment by KatKatKateryna** [comment]
Awesome, thanks!
More details on the same issue for the future reference: https://github.com/qgis/QGIS/issues/45646

**Pull request merged**
